// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-items.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-items.ts
var search_items_default = defineTool({
  name: "search_items",
  title: "Search lost & found items",
  description: "Search active lost or found item reports by keyword, category, location, or type.",
  inputSchema: {
    query: z.string().trim().min(1).optional().describe("Keyword to match in title or description."),
    item_type: z.enum(["lost", "found"]).optional().describe("Restrict to lost or found reports."),
    category: z.string().trim().min(1).optional().describe("Item category, e.g. Electronics."),
    location: z.string().trim().min(1).optional().describe("Partial location text to match."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, item_type, category, location, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("items").select("id,title,description,category,item_type,status,location,date_lost_found,reward,created_at").eq("status", "active").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (item_type) q = q.eq("item_type", item_type);
    if (category) q = q.ilike("category", `%${category}%`);
    if (location) q = q.ilike("location", `%${location}%`);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-item.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.23.8";
var get_item_default = defineTool2({
  name: "get_item",
  title: "Get item details",
  description: "Fetch the full details of a single lost or found item report by its ID.",
  inputSchema: { id: z2.string().uuid().describe("The item ID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("items").select("*").eq("id", id).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2(`No item found with id ${id}`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/list-my-items.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.23.8";
var list_my_items_default = defineTool3({
  name: "list_my_items",
  title: "List my reports",
  description: "List the lost and found item reports created by the signed-in user.",
  inputSchema: {
    status: z3.enum(["active", "resolved", "closed"]).optional().describe("Filter by report status."),
    limit: z3.number().int().min(1).max(50).default(20).describe("Maximum number of results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("items").select("id,title,category,item_type,status,location,date_lost_found,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/report-item.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.23.8";
var report_item_default = defineTool4({
  name: "report_item",
  title: "Report a lost or found item",
  description: "Create a new lost or found item report for the signed-in user.",
  inputSchema: {
    title: z4.string().trim().min(1).max(200).describe("Short title of the item."),
    description: z4.string().trim().min(1).describe("Detailed description of the item."),
    category: z4.string().trim().min(1).describe("Item category, e.g. Electronics."),
    item_type: z4.enum(["lost", "found"]).describe("Whether the item was lost or found."),
    location: z4.string().trim().min(1).describe("Where the item was lost or found."),
    date_lost_found: z4.string().trim().min(1).describe("Date it was lost or found (YYYY-MM-DD)."),
    contact_name: z4.string().trim().min(1).describe("Contact name for this report."),
    contact_email: z4.string().email().describe("Contact email for this report."),
    contact_phone: z4.string().trim().min(1).describe("Contact phone for this report."),
    reward: z4.string().trim().min(1).optional().describe("Optional reward offered."),
    additional_info: z4.string().trim().min(1).optional().describe("Any extra details.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("items").insert({ ...input, user_id: ctx.getUserId(), status: "active" }).select().maybeSingle();
    if (error) throw new ToolError4(error.message);
    return {
      content: [{ type: "text", text: `Created report ${data?.id}: ${data?.title}` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dmarkaigzovaqwpigtxe";
var mcp_default = defineMcp({
  name: "lost-and-find",
  title: "lost-and-find",
  version: "0.1.0",
  instructions: "Tools for the FindIt lost & found app. Search active lost/found reports, read a report's full details, list the signed-in user's own reports, and file a new lost or found report on their behalf.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_items_default, get_item_default, list_my_items_default, report_item_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
