// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmarkaigzovaqwpigtxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtYXJrYWlnem92YXF3cGlndHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzEzMDEsImV4cCI6MjA2Njk0NzMwMX0.IJ01ugvnjFNp4YT0mODR2IwzD337H3rWTuQRfONA_To";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});